### ISSUE TITLE
its not working what can i do ?

### ISSUE THREAD

**Issue by cowardtv** [Nyxonn/Lua-Bytecode-Deobfuscator#12]
![test2](https://user-images.githubusercontent.com/25543568/117784920-b93d6800-b24c-11eb-8eaf-cf94064a13fc.png)
![test3](https://user-images.githubusercontent.com/25543568/117784922-ba6e9500-b24c-11eb-8dc0-0c6655c55f31.png)

**Comment by Nyxonn** [comment]
It just deobfuascated you this lua bytecode and this is the result code. It's obfuscated many times.

**Comment by cowardtv** [comment]
than how can i deobfuascate it again if i dont have a saved file of the deobfuascated  one
