### ISSUE TITLE
Getting this please help

### ISSUE THREAD

**Issue by DegenTheo** [Nyxonn/Lua-Bytecode-Deobfuscator#14]
![image](https://user-images.githubusercontent.com/45525477/118722458-75d69100-b82c-11eb-90bc-026140521786.png)

**Comment by DegenTheo** [comment]
![image](https://user-images.githubusercontent.com/45525477/118722524-8a1a8e00-b82c-11eb-927f-aa684cbbef3b.png)

**Comment by BTNGaming** [comment]
https://i.imgur.com/cpehsDW.png

**Comment by Nyxonn** [comment]
Run the program as administrator. Also send me screenshot of the .lua file

**Comment by hamzehalawneh** [comment]
I have the same problem

**Comment by ScarletTeam** [comment]
Me too

**Comment by Mafios** [comment]
this tool have trojans lol :))

**Comment by LandonDeam** [comment]
I think it's assuming the username for the computer is Daniel, so you might just have to edit that part to be your actual username, and then recompile

**Comment by Nyxonn** [comment]
Release version will be there soon.
