### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by ShrimpScript** [Nyxonn/Lua-Bytecode-Deobfuscator#18]
Virus possibly, ran through VirusTotal: https://www.virustotal.com/gui/file/f752c1dd8df8a17b6b40d22d61c49ebcfed22e33c11cbb4cc66c23823a12314b

Possibly trojan please remove if it is malware. Beware.

**Comment by SergeantNorth** [comment]
Correct. Trojan is there.

**Comment by electrickid621** [comment]
noticed it also

**Comment by Nyxonn** [comment]
Yes trojan is in open-source app. Congrats skids :)
