### ISSUE TITLE
can i get help on this please ? 

### ISSUE THREAD

**Issue by juvian3211** [Nyxonn/Lua-Bytecode-Deobfuscator#3]
Hello i am getting this error whenever i try to run it on the script , i put the .lua file one time in release folder and another time in debug , but it won't work 
![image](https://user-images.githubusercontent.com/73201977/100558484-587e2c80-32b7-11eb-8339-8cba281eb2c4.png)

**Comment by Nyxonn** [comment]
Is it only a bytecode obfuscation or sth more?

**Comment by Nyxonn** [comment]
Remember to run it as administrator and also type, "filename.lua" with .lua
